### ISSUE TITLE
Active area of viewer small portion window on macOS

### ISSUE THREAD

**Issue by bal-agates** [lazarus-pkgs/panini#11]
Built Panini 0.73.0 from source today.  On macOS 10.13.6 with QT5 5.13.2 the "panini.app" essentially works except the active area, the area where the image is drawn, is a small portion of the application window.  See enclosure.  Resizing the window does not help.  In fact if you make the application window too small the picture goes out of view.

![panini_view_problem](https://user-images.githubusercontent.com/55847433/70361710-2115a500-1848-11ea-8c51-aa3c5e592c13.jpeg)

**Comment by jubalh** [comment]
Thanks for the report. Will try to check this soon.

**Comment by jubalh** [comment]
@bal-agates it works fine for me on openSUSE Tumbleweed with Qt 5.13.1.
Does this happen with every picture for you?
Unfortunately I don't have macOS and thus cannot test there.

**Comment by jubalh** [comment]
Still noc macOS to test. And no feedback.
