### ISSUE TITLE
No AppImage for the latest release

### ISSUE THREAD

**Issue by sbrl** [lazarus-pkgs/panini#13]
The latest release, version 0.73.0, doesn't have  an AppImage attached.

Version 0.72.0 (the previous version) does, but the latest version doesn't.

**Comment by jubalh** [comment]
That's right. I forgot how I created the orignal one so I omitted it :)

**Comment by jubalh** [comment]
@probonopd what would be the best/easiest way to create an appimage upon each release?

**Comment by probonopd** [comment]
@jubalh it can be automated using a continuous integration service like GitHub Actions or Travis CI.
Do you already have a working script for making the AppImage, and if so is it available somewhere?

**Comment by jubalh** [comment]
@probonopd for an older release I used OBS. Actually just now I found the project again: https://build.opensuse.org/package/show/home:jubalh/panini
It appears i still have the yml file that creates the AppImage in there. It's more than two years since I touched the stuff so I don't quite remember. But it seems even for the latest release (0.73.0) I planned to build one according to that repo.
Strange that OBS doesn't seem to build it. Have to look into this.
But having GH Actions setup might also be a good idea.

So this is the yaml I used: https://build.opensuse.org/package/view_file/home:jubalh/panini/appimage.yml?expand=1

**Comment by probonopd** [comment]
OBS is a great choice. Maybe you can resurrect it?

**Comment by sbrl** [comment]
Thanks, @jubalh! that'd be very helpful, because I'd rather use a precompiled AppImage than setup my own build infrastructure lol :P

**Comment by jubalh** [comment]
@sbrl panini is also in several distros: https://repology.org/project/panini/versions

**Comment by sbrl** [comment]
@jubalh Interesting! I was not aware of that. Sadly Debian/Ubuntu isn't one of those though (I use Ubuntu 20.10 myself), and I can't actually find _any_ software to preview / display panoramic photos that I can install via apt that is :-/

**Comment by jubalh** [comment]
Don't worry I'll try to create the AppImage soon. Hopefully the coming week :)

**Comment by jubalh** [comment]
@probonopd are you familiar with OBS? I'm not sure I build the AppImage correctly there.

This is the repository: https://build.opensuse.org/package/show/home:jubalh:panini/panini
AppImage yml file: https://build.opensuse.org/package/view_file/home:jubalh:panini/panini/appimage.yml?expand=1
AppImages: https://download.opensuse.org/repositories/home:/jubalh:/panini/AppImage/

But when I try to run this on my local openSUSE Tumbleweed I get:
```
panini: panini: no version information available (required by panini)
panini: symbol lookup error: panini: undefined symbol: , version 
```

**Comment by jubalh** [comment]
@probonopd ping :)

**Comment by probonopd** [comment]
Sorry, I don't know what might be causing this.
What happens if you run `--appimage-extract` and then run `./squashfs-root/AppRun`? 

Maybe you can see what is going on by running `strace -f ./Your.AppImage` and/or `LD_DEBUG=libs ./Your.AppImage`.

**Comment by jubalh** [comment]
I was not able to build the AppImage fine by adding `-bundle-non-qt-libs` to `linuxdeployqt`.

@sbrl I uploaded the 0.73.0 AppImage to the release on GitHub. Give it a try!
